image: java:8-jdk

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/distributions/SpecPro*.zip
      - build/distributions/SpecPro*.tar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check

after_script:
  - echo "End CI"